FROM golang:1.17-alpine as builder
RUN mkdir -p /root/.ssh/ && \
    apk update && \
    apk add openssh && \
    apk add --no-cache build-base && \
    apk add --no-cache alpine-sdk && \
    rm -rf /var/cache/apk/*
ARG CGO_ENABLED=0

#RUN go get github.com/nats-io/nats.go@v1.11.1-0.20210623165838-4b75fc59ae30
